# SPDX-FileCopyrightText: 2026 GARDENA GmbH
#
# SPDX-License-Identifier: Apache-2.0

open_valve:
  target:
    entity:
      integration: gardena_smart_local_preview
      domain: valve
  fields:
    duration:
      required: false
      example: 900
      selector:
        number:
          min: 60
          max: 10800
          unit_of_measurement: s
          mode: box

enable_output:
  target:
    entity:
      integration: gardena_smart_local_preview
      domain: switch
  fields:
    duration:
      required: false
      example: 900
      selector:
        number:
          min: 1
          unit_of_measurement: s
          mode: box
